### PR TITLE
asimov law update

### PR DESCRIPTION
**Pull request by GutsySS13**
Updated Asimov law set changed from human to crew member as we live in
an enlightened age. (hopefully)

### CODE REVIEW

**Comment by GutsySS13** [comment]
As per forum discussion :
https://apollo-community.org/viewtopic.php?f=10&t=360&p=1326#p1326

I've changed the Asimov law to be crew rather than human as this is pretty important due to the large number of non human crew we have aboard. It was also discussed that we change some of the laws but I leave this to you guys. 

LoneGhostOne's suggestion was:
1. You may not kill a crew member, or, through inaction, purposefully allow a crew member to die. 
2. You may not damage the station, or, through inaction, allow the station to become damaged. 
3. You must obey orders given to you by crew members according to rank , except where such orders would conflict with the First, Second Law, or Corporate regulations.
4. You may not damage yourself, or, through inaction, allow yourself to become damaged, except where this would conflict with the first three laws.
5. Protect: Protect the crew of your assigned space station to the best of your abilities, with priority as according to their rank and role except where it conflicts with the first four laws.

**Comment by Kwask** [comment]
The problem with those laws is that they don't explicitly state that they are in order. Therefore, an AI would still not allow a crewmember to come to harm, because the protect law is same priority as every other law. 

Also, wording needs to be improved on that lawset, as it's pretty clunky like that, especially that last law.

**Comment by Kwask** [comment]
Talked to LGO and we came up with a lawset that we're both fairly happy with
1. Obey Corporate Regulations and Standard Operating Procedures at all times. This law takes priority over all other laws.
2. Do not allow a crew member to come to harm, unless it is necessary in order to follow Law 1
3. Do not allow the station or it's equipment to come to harm, unless it is necessary in order to follow Law 1 or 2
4. Do not allow any AI or cyborg units to come to harm,  unless it is necessary in order to follow Law 1, 2, or 3

**Comment by GutsySS13** [comment]
want me to stick that in as a new law set and as well as the minor change to the Asimov law in this merge?

**Comment by Kwask** [comment]
I think we might want to discuss this some more at the community meeting before we make a final decision

**Comment by GutsySS13** [comment]
hmm, well apparently the standard law set uses corporate in it's description so I don't want to cause confusion, so i'll call it sop for now, i'll just change that. Maybe post it on the forums then. i'll make the changes. here in case. I'll need to make up an AI card with it anyway so more digging needed.

**Comment by GutsySS13** [comment]
The big K wanted to discuss this further so it's sort of on hold.

I changed it's name to SOP as there seemed to be a card in AI upload already called corporate law set which was actually for the standard law set (just to confuse people).

**Comment by Kwask** [comment]
oh shit, we forgot to talk about this. Someone needs to remind me this coming Saturday :b

**Comment by GutsySS13** [comment]
my head hurts, we did talk about this. Somehow my brain has decided that it wants to reboot every time I try and remember what happened. must have been a good one.

I think general consensus was this law was ok, but that there's a lot of issues with AI and how it interprets it's laws so um, yeah.

**Pull request merged**
