### PR TITLE
Hugs become High Fives

### PR DESCRIPTION
**Pull request by valzargaming**

### CODE REVIEW

**Comment by Kwask** [comment]
Maybe could random it so it picks between the two?

**Comment by lmas** [comment]
:+1: for random chance of a high five instead

**Comment by halworsen** [comment]
high fives when your throw mode is on, hugs when it's off?

**Comment by stuicey** [comment]
Secret handshake when both players throw mode is enabled

**Comment by Kwask** [comment]
yesss stu. gimme daps

**Comment by stuicey** [comment]
*dap

**Comment by BlueSushii** [comment]
What happened? Why soo many tags for this?

**Comment by halworsen** [comment]
this is the most important PR that's ever graced this repo with its beautiful presence

**Comment by lmas** [comment]
It's going to make you slightly gay too, what with all those rainbows.

**Comment by valzargaming** [comment]
What's up with all these tags?

**Comment by lmas** [comment]
Just a little bit of love for you :D

**Comment by valzargaming** [comment]
[I never asked for this.](http://s2.quickmeme.com/img/12/1264c9f620e5f490e005320d658fa9fba9433ff25eca4744cd58238699183556.jpg)

**Comment by Kwask** [comment]
Closing due to inactivity

**Comment by halworsen** [comment]
why not merge instead :japanese_goblin:

**Comment by stuicey** [comment]
Hugs > high five

**Pull request closed without merging**
