### PR TITLE
Kitchen Patchwork + Bonus

### PR DESCRIPTION
**Pull request by Rusty-Gravy**
Just un-goofing Kwasks' fix to my goof.

Also added test code to see if Mulebots will open airlocks or not. 
If it doesn't work, then no worries. (It's already broken anyway)

### CODE REVIEW

**Comment by nullbear** [comment]
why would you want to undo kwasks fix?

**Comment by Rusty-Gravy** [comment]
I don't think I am, am I? D:
I know that I'm fixing some bugs that his fix caused, and just making sure the Kitchen looks nice and can be used.

**Comment by Rusty-Gravy** [comment]
Just sorted the conflict out also somehow, so the merge is good to go.

**Comment by GutsySS13** [comment]
Step_x and Step_y are a definite no no for map editing. they are used by the animation system to move players (possibly simple animals too etc.) and if you use them on the map then it breaks player movement and they pop between tiles. always use pixel_x and pixel_y to offset objects from their default position in a tile. 

Any Step_x and Step_y's have to be removed from a map file for player animated movement to work.

My guess as to why mulebots (and possibly beepsky) isn't working properly is that one of the auto navigation beacons has been deleted or is in a wall somewhere.

**Comment by GutsySS13** [comment]
Having just had a quick and cursory look, (sorry had a busy week) I'm now going with the 'it's been deleted and that's why mulebots are screwed'.  They can't compute all their routes because one of their routes does not exist.

I suggest re-instating a delivery area in the bar for mulebots and you may find that they magically start working again (hopefully fix beepsky too) once they can compute all their destinations as valid destinations again, unless your hack involves just deleting bar from their list of designations that they are searching for.

**Comment by Rusty-Gravy** [comment]
I didn't offset anything, that's what I'm saying.
The objects spawn in with that offset already, I believe it has always been like that.

**Comment by Rusty-Gravy** [comment]
And I think you're likely right about that route thing.
At least with the new lines I've thrown in the mulebots should be able move from A to B (in terms of actually being able to get out of the cargo bay), even if it is a bit of a weird route.

**Comment by nullbear** [comment]
you're thinking of pixel_x and pixel_y for the offsets

**Comment by Rusty-Gravy** [comment]
step_y

Definitely step_y

**Comment by Rusty-Gravy** [comment]
Would step_y = 0 make a difference to the walking animations? 
I just thought that if we offset all the step_y to zero, but keep the variable there, then this issue can be resolved?

**Comment by GutsySS13** [comment]
All I can say is that using any sort of step X or Y is playing with fire, the fact that it may work as a negative is just plain luck and the fact it's working may just be a bug and should not be relied on in any way (-1 usually evaluates to false in most languages so maybe there's some dodgy maths somewhere). Change it to pixel_y as soon as possible as this is the proper way of offsetting things on the map.

> Would step_y = 0 make a difference to the walking animations? 

That would be fine as it's the default option and would be the same as you editing the file manually and just deleting the step_y part yourself, as you're not offsetting the object at all then.

**Comment by Kwask** [comment]
Never use step_x or step_y. Ever. Even setting the value to 0 still breaks the walking animations. It's an old deprecated variable that has since been replaced by pixel_x and pixel_y. If you ever need to offset an object's position, use pixel_x or pixel_y.

**Comment by lmas** [comment]
Hey @Rusty-Gravy think you can open up a new PR that's cleaned up and good to merge? This one is getting a little bit poluted with step_y stuff and there's a merge conflict too. 

I'll add in your fork sync guide myself though, so don't worry about that one.

**Comment by nullbear** [comment]
Im pretty sure Ctrl+Arrows automagically nudges the step_x/step_y of an object. So dont do that.

**Comment by GutsySS13** [comment]
I did a test with mulebots and adding back the kitchen/bar mulebot locations didn't magically make them work again, I think the access code has changed. Beepsky has his access in the main variables (mulebots don't) and in his access card (mulebots do have this). so it's not a routing problem.

-- On a side note beepsky is still bugged routing, I think it maybe a timeout or something. he always looses his route at the AI core west node.

**Pull request closed without merging**
