### PR TITLE
Sectors changes

### PR DESCRIPTION
**Pull request by Kwask**
FEATURES:
- [x] Space travel now occurs on the overmap
- [x] The old random-z method now applies to mobs and most obj
- [x] Lower instances, less lag, workers unite!

### CODE REVIEW

**Comment by lmas** [comment]
Looks interesting. What state is this in right now? I have only glanced over the code quickly, but it looks like you're at least able to travel to sectors on the overworld map now?
Could you explain more how the overworld works?

Did you cleanup those unused gateway maps so we can use them too?
Also, will you add some way to determine if a sector has any interesting features in it? As I wrote in #225.

**Comment by Kwask** [comment]
To travel the overmap, you simply need to go to the edge of a z-level, and then it prompts you if you want to traverse space. Once on the overmap, you'll get a world view, à la dwarf fortress world travel.

Traveling the overmap looks like this:
ss 2015-06-26 at 01 04 50

The little tiny gray dot with purple shooting out the back of it in the center of the screen is the spacepod.

The orange question marks are unidentified objects. By default the question marks won't be visible until after you scan for them. When you cross into a sector with a discovered object, you're prompted if you want to enter the sector. If you choose yes, then you're placed at the edge of that sector's z-level.

**Comment by lmas** [comment]
:+1: I love it. Way better than the old sector space. Kinda funny to see the station, eng. station and the ACE as tiny icons on it too.

I assume this is stable enough now so that you can enter those sectors? What maps are currently active and will show those question marks? Are you currently randomizing the secret sectors with new maps on each round start?

**Comment by Kwask** [comment]
Yup, it's all stable so far. The one thing I haven't gotten to test is the transition fade for passengers of spacepods.

I'm adding flags to sectors, so the station config levels are automatically populated, so adding more levels will be EVEN EASIER.

Currently only the apollo 1-7 are active, but we can change that soon

**Comment by Kwask** [comment]
Whoops, accidentally just moved the entire asteroid under the station. Now the Mining dock is actually a mining dock!

ss 2015-06-27 at 12 19 00

**Comment by nullbear** [comment]
xD i kind of like the way that looks though. Why not have zlevel asteroid below ace/asteroid?

**Comment by lmas** [comment]
Yes, I like that idea too. But might want to make it look more "below", so some poor newbie doesn't get confused and think you-can't-go-outside-because-there's-some-rock-in-the-way.
Could easily make a new turf for it too I guess, which you can paint the ACE level without needing a completely new z level beneath it.

**Comment by nullbear** [comment]
yeah xD I'm thinkin to have it only low enough to be under the docks (where you can walk outside to anyways) and the rest of the asteroid.

**Comment by Kwask** [comment]
Was thinking about allowing for the drills to drill into caves on the asteroid, which would be randomly generated. Then there would be things like ruins for xenoarch or monsters to fight. Loot too, but that's obvious

That's for a different update though :dancer:

**Comment by Midaychi** [comment]
You could keep that asteroid background but also have it slightly darker and occasionally have dust and tiny asteroids floating by on a lower zlevel than the station but higher than the background. Have them rotate with client matrix actions, similar to goone throw. That should be enough to illustrate that it's space and not walk-able ground.

**Comment by lmas** [comment]
Does Byond support multiple graphical z levels? Like background, foreground etc.?

**Comment by Midaychi** [comment]
Yeah that's how layering works in the first place.
I guess I said zlevel instead of 'layer'. Derp.

**Comment by Kwask** [comment]
There's already graphical z-levels, that's whats visible in the previous image. We don't utilize it, though, because you can see through the ceiling of floors below you.

Whenever I get around to refactoring z-levels, I can fix that issue, and add in cross-z airflow and such as well

**Comment by Kwask** [comment]
Could use some suggestions on how scanning for sectors will work

**Comment by lmas** [comment]
That's what I thought about the layers, but was unsure since it's Byond after all.

I would suggest you keep it simple for now and make the scanner work like the GPS spacepod verb (or whatever it was called).
In the future you could perhaps make both verbs be actuall equipment for the spacepods, merging the two verbs into some kind of telemetry part with it's own interface in a window. Better components for this part would increase the scanning range etc.

Edit: Could you also add in that space pirate asteroid gutsy added in recently? I think it's the perfect time to introduce that map.

**Comment by Kwask** [comment]
Taking the garbasteroid off of the to-do list for now until we get better sprites for it :recycle:

**Comment by Kwask** [comment]
Got problems with maploader, loading maps take 30 seconds to a minute per map. Not really sure what we can do about that in order to implement random sectors.

**Pull request merged**
