### PR TITLE
Added Mulebot Bar beacon

### PR DESCRIPTION
**Pull request by GutsySS13**
This fix re-instates the old Mulebot navigation beacon in the bar back room.

I had to move the ladder south 2 squares so also had to swap 2 tiles around in apollo-6.dmm, added mulebot beacon and delivery area from older map. I've also added a re-enforced piece of glass and glass doorway as the old area had these.

Here's how the area now will look:
New bar delivery area

and ladder moved under bar area:
under bar ladder move

I also noticed a bug with the mulebots that they didn't unload the crate into the unload area, but dropped it into the flaps, and they still didn't open doors properly.

The mulebots still don't open doors but do seem to path around ok. I did notice that beepsky seems to have an extra section in his variables with his door access whereas the mulebots just seem to have their door access in their ID card section only.

Their ID card door access is:
access_maint_tunnels = 12
access_cargo = 31
access_cargo_bot = 34
access_mailsorting = 50

which should be enough to get where they need to. I still saw beepsky pathing through the maintenance tunnels near the bridge rather than going to the station 13 logo and up to security so there may still be an issue with one of his navigation points there.

### CODE REVIEW

**Comment by Kwask** [comment]
Can't say I'm a fan of the ladder being in front of the door, which would mean the bartender would have to waddle around it to get into his office :hear_no_evil:

**Comment by GutsySS13** [comment]
want me to take down the pull and change it around a bit?

**Comment by Kwask** [comment]
just add your commits to this PR, it'll keep things organized :package:

**Comment by GutsySS13** [comment]
you do just walk over the ladder, you have to click the ladder or press the verb in the object tab to use it. (just don't look down)

**Comment by Kwask** [comment]
Yeah, I know, but it looks funky with the ladder in front of the door. It's like having a chair in front of the door. Sure you can pass through it, but realistically it'd be an obstacle that wouldn't be placed there

**Comment by GutsySS13** [comment]
ok, moved ladder up 1, AI holopad left, and on the lower level swapped the wall and ladder over. Ladder worked, didn't test the mulebot again

On a side note the editor behaved itself and only made 2 minor changes having butchered the files last time.

**Comment by Kwask** [comment]
I think the map editor was updated some in the most recent version of BYOND, might have something to do with that

**Comment by GutsySS13** [comment]
um, want me to re-do the whole pull? I can export it as a dmm and paste the 3 tiles in?

**Pull request closed without merging**
