### PR TITLE
Fixes AI burning to death upon touching the engine

### PR DESCRIPTION
**Pull request by StarSmasher44**
First one's free :P

Just kidding, I died so I had to fix it.

---
This change is [Reviewable](https://reviewable.io/reviews/apollo-community/apollostation/1387)

### CODE REVIEW

**Comment by Awantje** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/apollo-community/apollostation/1387)*

**Comment by Haldreithen** [comment]
Next time, follow the template that appears when you start a pull request. Next time, the pull request will not be merged and closed probably without notice.

**Comment by StarSmasher44** [comment]
Is the commit not explanatory enough? It's all you see anywhere any way. I'll remember to make my description look nice for you though next time I want to make a 2-line edit.

**Comment by InvidiaSH** [comment]
The reason for it is that we can keep issues and PRs organised and tidy.

Even though you may feel your PR is self-explanatory as it is, the normal format includes a checklist for maintainers, etc.

This PR lacks that, hence why @Haldreithen told you to format it correctly next time.

**Pull request merged**
