### PR TITLE
Wave propogation

### PR DESCRIPTION
**Pull request by Kwask**
Adds cellular automata functionality, and adds a vorbis-radiation wave to replace the supermatter burst.

Features:
- [x] Cellular automata 
- [x] Vorbis radiation wave
  - [x] Creates supermatter crystals where it passes
  - [x] Turns humans into nucleations

### CODE REVIEW

**Comment by Kwask** [comment]
Here's a webm of the wave in action https://drive.google.com/file/d/0B9LNmHO_PasjNU9EejhzZXYwRWM/view?usp=sharing

**Comment by nullbear** [comment]
Now to make walls/certain materials reduce the power of it.

**Comment by nullbear** [comment]
also it's much too visible. Can we knock off the sparkles unless you're
wearing mesons, and reduce the lighting to like 50% on the wave?

**Comment by nullbear** [comment]
by which i mean if you're wearing meson scanners, you see the particles,
otherwise, you see a wave of light only.

**Comment by Kwask** [comment]
If I can figure that out, that sounds like a good idea

**Pull request merged**
