### PR TITLE
510 Scheduling Changes

### PR DESCRIPTION
**Pull request by stuicey**
Updates scheduler to use tick_usage.
Removes btime dependency for scheduler
Moves solar panels into a separate processing queue
Adds a more efficient sleep check

### CODE REVIEW

**Comment by Kwask** [comment]
isn't btime more accurate?

**Comment by stuicey** [comment]
I think it is slightly more accurate, but it has a bunch of issues with cross-platform compatibility and different architectures in addition to the overhead of calling external functions.

**Comment by Kwask** [comment]
I could have sworn all of that crazy lag-free footage that someone posted on the subreddit was possible because of the precision of btime

**Comment by stuicey** [comment]
I've tested both implementations and btime is faster dealing with explosions and player events, however it is awkward for me to test with as it doesn't want to compile under x64. I think I'll make a few more changes and then re-implement btime for use on the main server.

However this will mean that local dev servers don't perform very well.

**Pull request merged**
