### PR TITLE
Updated xenoflora mutation based on nullbear's suggestion in #139.

### PR DESCRIPTION
**Pull request by lmas**
Per nullbear's comment regarding this change:

```
as far as i can tell, there's only like 6 colors that the plants can glow in, being two shades of violet,
red, and green. Mine sticks to those "basics" but allows them to vary quite a bit, and adds a 25%
chance for it to glow in a completely random color that has a rather high chance to glow in some
neutral-icky color.
```

Wanting input from someone else besides just me.

### CODE REVIEW

**Comment by Kwask** [comment]
So this just makes xenoflora plants glow random colors? I'm not really sure that random rainbow vines will look great at all :8ball:

**Comment by lmas** [comment]
He updated it some at https://github.com/stuicey/ApolloStation/commit/30ad811ff06a92b89708e4fa793ab748b44706d4#commitcomment-11485404

**Comment by nullbear** [comment]
The original vine glow colors were "red, orange, yellow, green, blue, violet" This changes it to a range of reds, greens, violets, and 'whatever' instead, because hey, it's more fun that way. Note, this just changes the glow colors, not the vines themselves.

The original, and main intended change, just makes it possible for the vines glow color to change during a mutation, because the way it was originally coded was uh... poor.

**Comment by nullbear** [comment]
sorry... could you also change it again, what is this, like the third time? -.+ xD 

remove else from 'else if (prob(degree*2)'

Move 'if biolum & prob(degree)' codeblock underneath of the other, and change it to 'else if (biolum)'

**Comment by lmas** [comment]
I finally took the time to complete this thing and commited it with 3843f8a1efa774a387c77cb5c19d495c55864321.

**Pull request closed without merging**
