### PR TITLE
Kitchen/Hydroponics Fixes

### PR DESCRIPTION
**Pull request by Rusty-Gravy**
I've noticed a few bugs/issues with the Kitchen and Hydroponics, so I conjured this little overhaul up.

Kitchen:
- Added a dropper. New players will recognize it and understand it, using it to add 1 unit of salt/pepper/amantoxin to their deep fried grilled mint flavoured giant gummy bears.
- Added a small section to the "Chef Recipes" briefly explaining the
  kitchen machines. _Probably need to update wiki too, I'm happy doing
  this if you guys set up an account for me._
- Switched the candy machine and cereal maker around to prevent a bug
  where objects, including mobs, would appear to stand on one half of the candy machine when stood 1 tile north.
- Tweaked the sprite for the cereal maker, so it doesn't appear to be hovering over the side when on a 1x1 table.
- Fixed a bug where the Dinnerware vending machine was able to vend a /obj/item/weapon, instead of the /obj/item/weapon/butch (Which doesn't
  actually exist! :cry:)

Cold Room:
- Moved some things around for space.
- Added the throwpass = 1 variable, this is so that moving a new
  container underneath the gibber is possible.
- Created a new freezer subtype with new bloodied sprite.
- Added a mop and bucket, it makes sense.

Hydroponics:
- Tweaked the windows so that the Farmbot no longer gets confused by the bottom-left dirt.
- Added an easter EGG to Kwak.

Misc:
- Updated description for the dropper and robodropper.

### CODE REVIEW

**Comment by Rusty-Gravy** [comment]
Christ I'm so messy at using Github...
Apologies.

**Comment by nullbear** [comment]
hrm... I was pretty sure only last week i hacked the dinnervend and nabbed a cleaver...
You can transfer 1u to food using condiment dispensers, or y'know, salt and pepper shakers.
How do you wet a mop using the bucket? Never worked for me, had to use janicart.

**Comment by Rusty-Gravy** [comment]
The /butch item doesn't exist in the path that Dinnervend asks for, so for now I've disabled the option.
I had no idea you could do under 5 units using shakers, but I think the dropper would be a good addition as it's easier to use, and a little more newbie friendly as it's recognizable.
The bucket I used is the mop bucket, so you just fill that with water and it should work fine.

**Comment by nullbear** [comment]
Yeah i agree. Just thought you should maybe at least be aware that there IS a cleaver still in the code somewhere if you want to look for it.

**Comment by nullbear** [comment]
"4,991 additions, 4,990 deletions not shown" what.
You added ONE darned thing... How did you make it bitch so hard?

**Comment by Rusty-Gravy** [comment]
I'll have a look for the cleaver later, I'm sure it's hiding around.
And I honestly have no idea how I manage to make Github scream so loudly

**Comment by Rusty-Gravy** [comment]
:+1:

**Comment by Rusty-Gravy** [comment]
Should I set ALL crates so that you can throw items over them?
Because they inherit everything from closets the game thinks you can't do that.
IMO you should be able to throw a pen over a crate.

**Comment by GutsySS13** [comment]
> nullbear commented 7 hours ago
> "4,991 additions, 4,990 deletions not shown" what.
> You added ONE darned thing... How did you make it bitch so hard?

Well without going into too much depth, the map is made up into an array, when you create a new tile entity that requires a new entry then it has to shift everything down one and that's what it looks like it did here. 
It's tricky to work out how to make it not do this, but placing similar objects on similar tiles and entities will save these array rows. It's all that aaa,aab etc stuff that makes the map get drawn at the bottom of the map file. So for efficiency it would be best for all downward facing lights to have the same floor and no dirt, or all mouse tiles to have a piece of garbage under them, etc.and be consistant. If he had moved the whole contents of the the tile as it was (piping, cabling etc) then it wouldn't have made a new entity, but it's not always possible.

**Comment by Rusty-Gravy** [comment]
Ah. Nice explanation, thank you c:

**Comment by Kwask** [comment]
The real cleaver is in ghetto surgery if you want to find its type path

**Comment by Rusty-Gravy** [comment]
It's okay, I found the kitchen cleaver and re-added it to the Dinnerware vendor in the "Cleaver Fix" commit. :)

**Comment by Kwask** [comment]
aight, awesome, I think this is ready for merge then

Also, I'll go ahead and get you an editor's acc on the wiki

**Comment by Rusty-Gravy** [comment]
Awight thanks mane

**Pull request merged**
