### PR TITLE
Eng outpost wall fix +particle accelerator added

### PR DESCRIPTION
**Pull request by Awantje**
added a pa and fixed the wall on the engineering outpost

### CODE REVIEW

**Comment by Awantje** [comment]
I cannot compile or run on the computer I am using currently so sorry that I could not test if the singulairity engine actualy works or not.

**Comment by Awantje** [comment]
I just added a rust aswell.

**Comment by Awantje** [comment]
I have been able to compile and test it now. Have seen the pa make a singulairity so that works. The rust I have also seen running.

**Comment by Kwask** [comment]
What is "pa"? Is it particle accelerator?

**Comment by Awantje** [comment]
yes, somehow the singulairity is not growing taking a look at that right now.

**Comment by Awantje** [comment]
I am updating it the longer this stays up with better engine builds. THough you can set them up already!

**Comment by nullbear** [comment]
coll ya

**Comment by Awantje** [comment]
proof the sing works http://gyazo.com/718465b0b1bd7b6b10e40ad87e19649a

**Comment by lmas** [comment]
I don't know how yet, but you've managed to break the PR so we can't merge it in without diving into a terminal :p

**Comment by GutsySS13** [comment]
One thing you may want to consider is having the field generators in the middle not align. This means if 2 or more engineers are outside turning them on there's no chance of them connecting across the gap (they have quite a range). Once they are on they will throw people away from them if they come near trying to turn them off again (highly amusing though so you may want this and good for teaching people lessons and makes setup more dangerous). I did something more along these lines if you want the dmm flie: https://drive.google.com/file/d/0Bw3ZV7xxvq78ZVJMa0hMRDctSHc/view?usp=sharing

**Comment by Awantje** [comment]
If there are space tiles between them they will not connect

**Comment by Kwask** [comment]
That's not true, the old singularity engine had lots of space tiles between the field generators

**Comment by GutsySS13** [comment]
if you just want a particle accelerator/singlo generator added to the derelict I could add one in a merge if you want. be aware there are secret issues I'm not prepared to say as to why it's incredibly dangerous though (where's that evil grin icon). It would be quite a quick job even though i'm working on my pirate asteroid at the mo, I could whack something together in a day or two as have a drop in replacement for our current engine room ready to go. (we need an evil grin icon)

**Comment by Kwask** [comment]
Since its been more than half a month since anyone has touched this, and the merge error hasn't been resolved yet, I'm just gonna close this PR

**Pull request closed without merging**
