### PR TITLE
Autoinjectors can be repaired using screwdrivers

### PR DESCRIPTION
**Pull request by Hate9**
Figured it made sense if these could be repaired somehow.

### CODE REVIEW

**Comment by Hate9** [comment]
I suppose I'll reopen this on Sunday.

**Comment by Kwask** [comment]
I'm not sure this is a good balance. Autoinjectors are cheap to get, but can only be used once. If they become repairable, then there's no reason to get a parapen.

**Comment by Hate9** [comment]
But does it really make sense if they're completely irreparable after being used?

**Comment by Kwask** [comment]
It makes sense gameplay-wise, yes. Additionally, if its supposed to be a sterile tool, you dont want to be reusing it between multiple patients in critical condition.

**Comment by Hate9** [comment]
I suppose that makes sense.

**Pull request closed without merging**
