### PR TITLE
Supermatter Fusion Stuff

### PR DESCRIPTION
**Pull request by nullbear**
Oh hell, there's a bunch of stuff...
- Supermatter efficiency reduced from 1.0 to 0.4.
- Smacking supermatter shards or entire supermatters will raise the
  smlevel
- Supermatter explosion and delamination nerfed. Explosion scales with
  smlevel
- Supermatters of different stages now glow different colors.
- Fixes tongs being able to pick up shards when they are already holding
  something.
- Hitting a shard with tongs carrying a shard, will cause the shards to
  fuse.
- High-Level SM growths have a chance to delaminate into lower-level
  shards.
- SM is able to take more damage when at higher levels. This makes it
  delaminate faster, and seem more unstable.
- For each stage of the SM, the explosion point is raised by 250.
- Supermatters with a level above 1 have a chance for "critical
  failure". The damage inflicted by, and probability of a failure
  increases with smlevel.
- Supermatters are drawn to eachother, and try to pull shards into
  themselves.
- The amount of Nitrogen needed to stabilize the oxygen reaction
  increases for each stage. At stage 8, the supermatter is just barely
  able to react with the environments air (79% nitrogen; 21% oxygen),
  above stage 8, the supermatter will react with station air.
- Supermatter loses power slower at higher levels. This makes it
  possible to produce more power, but also makes it harder to maintain.
- The supermatter produces more phoron per mole of oxygen reacted at
  higher stages.
- The supermatters "gas efficiency" rises with its level, capping out at
  stage 10. At stage 10, it is able to react with all the oxygen in the
  environment per-process, and produces 5 moles of phoron for every 1 mole
  of oxygen.
- radiation and hallucination is buffed with stronger SM's
- The SM is able to power collectors 2 tiles further for each level.
- Delaminations now use smlevel. A Delamination of lvl 2 is able to
  produce shards of level 2 and under.
- [x] TODO: Sprite different SMlevels for shards, and get rid of the god-awful attempt at color blending.

### CODE REVIEW

**Comment by lmas** [comment]
Kablooey
According to null it's the biggest explosion it can make on the high level SM cores, after he nerfed his "original" one. Apparently it's about the same size as the current SM.

**Comment by nullbear** [comment]
Nerfed explosions again, it caps at about 6 tiles smaller than the above image.

Also to note, added healing effect when attacking nucleations with supermatter shards, and a bunch of other tweaks here and there for balancing.

**Comment by nullbear** [comment]
Made a big commit to the SM. Long but not necessarily accurate details here:

## Using Nitrogen

engine loses power quite a bit faster. In about one hour, it will go from 400,000W 

to 0W If you are using the standard startup. At this rate, you'll have to constantly 

return to charge the engine in order to keep the station running at full power. 

Nitrogen is completely inert, and will have no effect on the engines reaction 

cycle, and for this reason, makes for an effective "control" gas by dilluting the air, 

and limiting the percentage that is able to react.

## Using Carbon Dioxide

Carbon Dioxide can be used to slow the power decay rate when used with a 

sufficiently high enough quantity of both itself and nitrogen. Carbon Dioxide is 

consumed quickly, and produces quite a bit of power, but does not have the same 

reactivity as oxygen, so is safe to be used for cold-starting and slowing power-

decay, but because of the consumption rate, will need to be refilled often. 

## Using Oxygen

Oxygen is somewhat reactive, and will cause the engine to produce phoron when 

used as part of the coolant gasses. In high-volumes, it is extremely dangerous to 

use in the engine, due to producing phoron and being an oxidant. In smaller 

amounts, or with a rapidly cooled and filtered system, it can be used to reduce 

power-decay and even produce power, without having to refill it as often as 

Carbon Dioxide. The more oxygen that is used, the more the decay rate will be 

slowed, but also the more likely it is to react with the engine dangerously. 

Because of the way oxygen reacts with the engine, it can be used to raise the 

"idle" power of the engine.

## Using Phoron

Phoron is a key-component to restoring the engine's integrity. Due to its high 

heat capacity, it can be used as a very efficient coolant. As well, low 

temperatures encourage new crystal growths on the supermatter. So long as the 

engine is below it's critical temperature, phoron can be used to repair the engine. 

As always, phoron is flammable, and if you're gunna use it, try to reduce the 

amount of oxygen in the engine. (see Meltdown)

## Using Nitrogen Oxide

Nitrogen oxide has the unique effect of having absolutely no beneficial effect on 

power production with the engine whatsoever. In fact, it actually siphons power 

from the engine. I guess... if you really wanted to... you could use it for powering 

down the engine for moving, stabilizing, reducing engine temperature, fusion, 

and for when you decide to leave the station.

## Supermatter Fusion

Supermatters can be fused together, which will often cause a restoration of 

integrity, and release a large amount of power. A fused supermatter will emit light 

in different spectrums, as well as produce exponentially more power. However, it 

also consumes gasses faster, and is more unstable. It will produce more energy 

from gasses such as oxygen and carbon dioxide. It is able to maintain higher 

power levels with slower decay.

## Critical Failure

High-Level Supermatters will have a chance for critical failure. The more 

advanced the engine is, the more catastrophic the failure will be, even to the 

point where it will delaminate instantly.

## Suffocation

At High-Level stages, the supermatter begins to require oxygen in order to 

function properly. The higher-level the supermatter, the more oxygen it requires. 

If the supermatters oxygen quota is not met, it will start taking damage, and 

decomposing into phoron at an increased rate.

## Engine Meltdown

When the engine reaches its critical temperature, phoron is no longer capable of 

repairing crystal structures, and the engine will gradually take damage. The more 

unstable the engine is, and the hotter the temperature, the faster its integrity will 

be lost. Phoron will now infact increase power as it destabilizes, causing the 

engine to heat up faster, but simultaneously causing power output to double. 

Using this info and careful control, it may be possible to "ride" the edge of the 

critical point in order to increase power output drastically. There are several 

ways that the engine can melt down:

---

Overcharging. The power from the engine is generating too much heat.
This can be resolved by raising the heat-capacity of the engine, using more 

coolant, siphoning power from the engine, or venting the core to space.

---

Suffocation. This will only happen with high-stage engines. The engine does not 

have enough oxygen, and will take damage. Since this isn't caused by heat or 

power issues, injecting phoron and a safe amount of oxygen should be enough to 

repair it.

---

Engine Fires. The dangers of using a high-volume oxygen coolant. When the 

engine catches fire, reduce the amount of oxygen as soon as possible, and vent 

the core to space. Since the temperature increase is caused by fire, and not 

overcharging, siphoning power is not necessary.

---

Critical Failure. Critical failures are caused by impurities in the supermatter 

crystal, as well as instabilities caused by fusion. If the core is cold enough, you 

can easily repair the damage to the crystal by injecting phoron. Critical failures 

can result in instant delamination in high-level sm's, so it's recommended to 

operate using a lower level sm, or at a safe distance from the station.

## Engine Fire

Using high-levels of oxygen in the engine can cause a phoron-fire reaction. Much 

like the engine meltdown, it could potentially be possible to "ride" the edge of 

critical temperature with this, however, the power output has the potential to triple 

due to carbon dioxide gas being produced as well as oxygen and phoron. 

Because of the nature of fires, it'll eventually burn out. If there is a small enough 

quantity of gas in the core, it'll often be fine to let the fire burn itself out. 

Occasionally if your coolant loop is supreme, you may even want to feed it more 

oxygen to keep it going.

**Comment by Kwask** [comment]
How easy does this make the supermatter for novice engineers? People's biggest complaint about SM right now is that its already too difficult to set up and maintain

**Comment by stuicey** [comment]
Could we maybe not have the super matter explode when an admin deletes it? 

Supermatter/Del()

**Comment by lmas** [comment]
Huh, I always thought the complaints was that the SM was "fire and forget"
and boring. But this is turning it into a really advanced feature. More so
than the atmos stuff (maybe).

And I think it's going to be really hard too, considering the lack of
available gas cans for the engineers, which I always felt was a big issue
and the most limiting factor when modding the engine.

**Comment by Kwask** [comment]
For average engineers its fire and forget, but every novice engine complains about how it's much more difficult to set up than the singularity

**Comment by Kwask** [comment]
whoops, didn't mean to close it

**Comment by lmas** [comment]
Right, so this is going to be way overkill for a newbie then. Need a better way to simplify things, while still having the option to do nullbear's kind of grand optimizations. Which is too bad, I like how this ties in with the new desub lab.

Edit: Also off topic, you guys really need to scale down your commits. It's going to be hell when trying to revert a couple of lines in a +200 lines/20 files commit. "Commit early, commit often" is a popular mantra and best practice when working with git and friends. Sure, I make a big commit too sometimes, but most often I try to keep each commit to it's own logical block (and only it's relevant files).

**Comment by Kwask** [comment]
Could make it so the default SM is very safe but not great for optimizing. Then as you increase the staging, the more dramatic the effect of these gasses are. That way, a newbie, who won't be messing with staging, doesn't have to worry about all of the complex gas stuff

**Comment by nullbear** [comment]
At stage one, it's very easy to set up. It's as easy as the standard setup. The complex gas stuff only becomes something you need to know about after fusing the engine at least once.

I'm fucking around with the emitters though. It might be possible to leave the emitter running on stage one without consequence, but im not totally sure yet... Most of the stuff you're worried about needs to be tested during an actual round to determine how much easier the engine needs to be at stage one.

Also, the SM doesn't explode when deleted. I be deletin' that shiz all day'n'night! You might be thinking of crystal growths though.

The power gotten from the emitter was reduced quite a bit. I find myself using a multitool paired with the emitter to see how quickly the sm is charging, charging it about 150% of what i need, and returning every hour or so to recharge it. At least, that's my goal with it. As of yet it still decays a liiiiittttle too fast.

**Comment by nullbear** [comment]
As well, im not really sure why, but the SM starts about half-charged at round-start. This isn't really an issue, as the power decays pretty quickly, and might actually give engineers more time to set up the engine, and take less time to set up.

derp. was using debug verb setup-supermatter which charges the engine somewhat.

**Comment by nullbear** [comment]
Engine produces "enough" power to run the station using 2 canisters of N2 and 8 emitter shots at stage one, with very low likelihood of taking damage. Using the simplest (and safest) setup, there is no chance for engine fires to occur. Stage 1 is incapable of critical failure or suffocation. Setting up the engine shouldn't 'feel' any different in stage 1. 

Oh yeah, and the supermatters started doing what they're supposed to do properly... It's now EXTREMELY dangerous (for non nucleations) to be near more than one supermatter.

Oh yeah, and touching the SM as a nucleation rejuvenates them. Probably going to add a nerf eventually so that it causes them to pass out for a short time or something.

**Comment by nullbear** [comment]
See new PR to merge. Github hates me.

**Pull request closed without merging**
