### PR TITLE
Bug Assassination

### LINKED ISSUE #147: Spacepod fabricators cannot be constructed (but can be deconstructed)
Upon removal and reinsertion of the circuit board, the machine frame will not accept any component parts and doesn't request any. Attempting to screwdriver it together in this state doesn't work either.

### LINKED ISSUE #186: Paper bugs
I mean, i guess i should have maybe tested the code before i made a pr, but:
- [ ] Fax machine construction is bugged as a result of being a child of photocopiers
- [x] Hand labellers dont use labels. Not my fault.
- [x] Filing cabinets need variety like comfy chairs or whatever
- [x] Antilogo doesnt work. I mean, i dunno why, but i'll figure it out.
- [x] Paper bins are not constructible, and do not drop papers that have not been added. That's no fun.

### LINKED ISSUE #549: Catametallic Alloy doesn't stack when using machinery
Stacking machine in mining?
Or ore processor.

Working on this already, Is there a way for me to add my own labels?

### LINKED ISSUE #553: Stray connector port
Dunno what it's doing there, but there's a connector port just outside of ACE for some reason.

idk

### LINKED ISSUE #561: Crew Transfer vote says failed when vote doesn't pass
I screwed something up. Already fixed.

### LINKED ISSUE #565: Can't pick up runtime!
Dragging runtime onto you opens the clothing screen now instead of picking up.

### LINKED ISSUE #566: Rats are stuck inside rat king when it dies
Rats should drop.

Already fixing, made for paperwork.

### LINKED ISSUE #567: ACE anomaly isolation room unusable.
The ACE isolation room where you're supposed to be able to safely expose alien anomalies to different gasses doesn't work. The vents/scrubbers don't work and you can't even de-tile the floor to look at the problem. This takes away a third of the possible research you can do on anomalies as some of them only react to atmospheric conditions. 
You can connect a canister to the pipes and pump gas into them, but it all stays within the pipes, since the vents don't work. You can also retirieve the gas with the other connector port, but you still can't make it flow into or out of the room.

### LINKED ISSUE #568: ACE has no nanopaste for spectrometers
Spectrometers need nanopaste to be repaired and remain operational, but there's not a single tube of nanopaste in the whole research area of ACE. This means that anyone playing xenoarcheologist or anomalist is eventually not going to be able to carry out their tasks.

### LINKED ISSUE #569: Alloy Synthesizer can't be built
Already fixed
# Paperwork

### PR DESCRIPTION
**Pull request by runedog48**
- Fixes #186 ( Fax machines can be constructed now )
- Fixes #549 ( Catametallic alloy gets stacked via machine now )
- Fixes #553 ( Removed random connector port )
- Fixes #561 ( Failure message doesn't appear anymore when vote doesn't pass )
- Fixes #565 ( Runtime can be scooped up into your arms again )
- Fixes #566 ( Rat king drops rats on death now )
- Fixes #568 ( Mass Spectrometry room has Nanopaste now )
- Fixes #567 ( Added air alarm to isolation room as well as laptop )
- Fixes #147 ( Spacepod Fabricator can be built now )
- Fixes #569 ( Alloy Synth. can be built now )

Merge at will

### CODE REVIEW

**Comment by runedog48** [comment]
Exams and stuff this week, won't be super active.

**Comment by Kwask** [comment]
S'all good, hope you do well on your exams :white_check_mark:

**Comment by lmas** [comment]
Looks like that last commit borked on the `step_[xy]` check. You should avoid setting that variable for some good reason I can't remember. And unfortunately I can't remember what to use instead, either.

**Comment by stuicey** [comment]
if you set step_[xy] then byond assumes you are using a custom movement setting so disables the glide animation. Use pixel_[xy] instead if you just want to offset an image.

**Comment by runedog48** [comment]
That was already fixed before I pushed the commit ( I even tested it in my private server ). Not sure what went wrong here.

Edit: Probably because I just set the values back to 0, instead of resetting to default triggering the build failure because technically the values are set ( at 0 ) even though it doesn't cause the movement thing.

**Comment by runedog48** [comment]
Ready for merge.

**Comment by valzargaming** [comment]
Double checked everything, looks good!

**Comment by lmas** [comment]
On the behalf of Me, Myself and I, I'm awarding @runedog48 a medal of
excellent performance
for your services in the game bug wars.

**Pull request merged**
