### PR TITLE
Adds Alloyed Glass

### PR DESCRIPTION
**Pull request by nullbear**
Adds a few different types of alloyed glass, each with different
properties. Also makes phoron glass obtainable via mining.

Phoron glass is fire-resistant/fireproof and 3-4 times stronger than
reenforced glass.

Uranium glass is 3-4 times stronger than reenforced glass, and glows in
the dark oooh.

Tinted glass is just as strong as the basic counterpart, and is opaque.

Diamond glass is 4-7 times as durable as glass, and when shattered, will
drop diamond shards. (unsmelted ore.)

Recipes for all of them:
phoron glass = 2 sand:1phoron alloyed
uranium glass = 2sand:1uranium alloyed
diamond glass = 2sand:1diamond alloyed
tinted glass = 2sand:2coal alloyed

Mapping stuff is me just replacing old tinted windows with new tinted
windows.

I wanna make a cool glowey base.

### CODE REVIEW

**Comment by Kwask** [comment]
I like this :D +1

You should redo the reinforcing code, though. Give glass stacks a var that hold their reinforced type, so you don't have to make duplicate code for every different type of glass. Also, you should add each material type to the materials list. For exanple, Give uranium glass "glass" and "uranium" in their materials list.

**Comment by nullbear** [comment]
glass just uses "reinforced" to determine whether it's reinforced or not. I was too lazy to make it sleek and reuse reinforcing code, so i just copy pasted the same procedure over to each glass type because it was easier. And yeah i was gunna add the materials. but i wasn't sure what they were called... so i just used plain glass for the time being.

There's also a bug where diamond glass windows dont drop diamond shards. idfk why they dont drop diamond shards. please tell me why.

**Comment by nullbear** [comment]
do you think we should have full-windows looking similarly to your walls or no? I think it looks "alright."

**Comment by Kwask** [comment]
Nah, when we tried that when we first introduced the windows, people didn't like the wall-esque sprites for windows

**Comment by nullbear** [comment]
well duh... your versions were bad. :I

**Comment by Kwask** [comment]
dunno how you can make glass windows that look like my walls without making them look like the glass windows that I made to look like my walls :confused:

**Comment by nullbear** [comment]
xD my windows look like a mix between your glass walls and the original window sprites.

From what i saw of your old windows, the issue wasn't you trying to make them look like the walls, but rather the way the windows looked in general. I also added a little bit to smoothwall so that there is an alternative bottom to some of the states. This makes it so that when a wall connects with a door, you can still see the split between the wall and the door. this applies to windows as well. It makes it so that walls will still blend with windows, but the material wont magically change from metal to glass.

**Comment by nullbear** [comment]
this is what it looks like right now with the alternate bottoms.
image 
The windows are still too pale atm though, making them darker.
You can see what the "alt-bottoms" i added does with the wall left of the kitchen shutters.

**Comment by stuicey** [comment]
Until someone thinks of a way to keep the functionality of normal windows this won't be happening. 

A major gripe for a lot of people is removing ghetto airlocks.

**Comment by nullbear** [comment]
this doesnt affect thin-windows, only full-windows.

**Comment by nullbear** [comment]
After some minor tweaks (which took a damned age to do, for some reason): 
image
Notice how the slim-windows are still the same (at bottom), this only applies to walls and full-windows.

**Comment by Kwask** [comment]
Go ahead and take the "dont merge" tag off when you're ready for this to be merged

**Comment by nullbear** [comment]
alright

**Pull request closed without merging**
