### PR TITLE
Dispensers

### PR DESCRIPTION
**Pull request by Fleegle2000**
This would add sacid and space cleaner dispenser code and icons (but doesn't add them to the map).

### CODE REVIEW

**Comment by Awantje** [comment]
would it be hard to give botany unstable mutagen. or to give xenoflora one.

**Comment by Kwask** [comment]
I'm fine with the sacid dispenser, but I don't want to make chemistry obsolete by giving every other department all the chemicals they need. That sort of power creep is why cargo is currently needed by no one

**Comment by Fleegle2000** [comment]
Yeah I see your point. Anyway, I couldn't figure out how to place the dispenser on a wall but only be accessible from one side of the wall, so I didn't add it to the map.

**Comment by Kwask** [comment]
To do that, you put it down on the side of the wall you want to access it from, then modify the pixel_x and pixel_y until the icon is shifted to where you want it to be

**Comment by Fleegle2000** [comment]
Okay. I tried that but was still having issues. Also, is there something special I need to do when compiling map changes? I was reading something on Baystation about running MapMerge to reduce the number of line changes, but I wasn't sure if you guys usually do that.

**Comment by Kwask** [comment]
No, just need to make sure any changes you make are on the most updated version of the map

**Pull request merged**
