### PR TITLE
Adds Omnitool. Also Makes Light replacer refilleable with boxes.

### PR DESCRIPTION
**Pull request by nullbear**
Adds omnitool, a pocket-sized tool with a built-in crowbar, screwdriver,
welding torch, wrench, wirecutters, and knife.

The CE has one in his office, a more effective syndicate variant is also
hidden on the station somewhere. It's also possible to purchase one
using a coin from the engivend in engineering.

I recommend the syndicate variant be worked into a new traitor item. It could replace the fully loaded toolbox for the roboticist/ce/engineer/assistant, or could be a 3tc item as it's more effective than the toolbox.

### CODE REVIEW

**Comment by nullbear** [comment]
The knife has about the same effectiveness as the plasteel butterfly knife. The welding tool holds less than 1/3rd the standard welding tool. I haven't implemented auto-tool-choosing yet.

**Comment by nullbear** [comment]
As you can probably presume. Tapping the light replacer with a box of lights (it doesn't need to be labelled as lights, merely be a box with lights in it.) will attempt to fill the light replacer with as many lights from the box as it can hold.

**Comment by stuicey** [comment]
Sounds very OP, I believe we talked about something like this in the past as a possible top end science item though.

**Comment by nullbear** [comment]
the light replacer..?

**Comment by Kwask** [comment]
Pretty sure he means the omnitool nully :p

Anyhow, I think it makes sense that the CE has one, just so long as they don't become commonplace

**Comment by nullbear** [comment]
Yeah there's also only one in the engivend, and the syndieone is probably only gunna hang around for a short while till it gets implemented into a kit. But yeah, it's useful as all hell and definitely shouldn't be commonplace, and at least be quite difficult to get your hands on. (the description is literally something along the lines of being a toolbox that fits in your pocket... Syndie version is a torture kit in your pocket)

**Comment by Kwask** [comment]
Go ahead and add the "ready for merge" label when you're ready

**Comment by nullbear** [comment]
I don't even know how... but it's been ready to merge for a while.

**Pull request merged**
