### PR TITLE
The spanning

### PR DESCRIPTION
**Pull request by stuicey**
Removes all instances of text colour macros.

Impossible to test due to number of modifications.

### CODE REVIEW

**Comment by Kwask** [comment]
this is a scary one :fearful:

**Comment by BlueSushii** [comment]
Will this fix all the colors in chat?

**Comment by stuicey** [comment]
If it all works properly it should terminate colours that have been used in a line of text so they don't just carry on until another macro changes them.

**Comment by lmas** [comment]
~~Hell yeah live testing. Let's do this~~ Hey look, it completed the compile. Since it passed The Test we might aswell merge it in. Who wants to do it? :D

**Comment by stuicey** [comment]
I take no responsibility for any issues that arise

**Comment by Kwask** [comment]
yes you do :>

**Pull request merged**
