### PR TITLE
Suggestion/change to brig entrance buttons

### PR DESCRIPTION
**Pull request by GutsySS13**
Here's a suggestion to the entrance to brig. I've made a forum post about it for discussion there, maybe a vote can take place too, so feel free to put this on hold or whatever.

The light switch buttons are quite small and neat so take up a lot less space than normal switches, I made them a different colour so hopefully people won't get confused but other than that they have the same hover text etc as the original buttons. 

At the moment the icons for them are in /icons/apollo/objects.dmi where you have your tables and stuff and I wasn't sure where to put them. The game is looking for a number of button names so I can't really change them without changing the code so it may be better to move them to separate files if you want different switches (i'd really like a proper brig panic switch to shut the place down for example rather than the rather boring regular switch). Icons are doorctrl0, doorctrl,  doorctrl-p and doorctrl-denied (although denied doesn't seem to be called for some reason) and are used by door_control.dm.

Anyway let me know. it just seemed to be a bit more logical to me to have the top button open the top door etc.

oh before i forget here's what it looks like:
proposed image

### CODE REVIEW

**Comment by Rusty-Gravy** [comment]
Now that I can see what you mean, I think this is a good idea to implement.

**Comment by nullbear** [comment]
I agree, makes sense.

**Comment by lmas** [comment]
Really hard to click though, better not minimize any panic-y buttons because, you know, emergencies and stuff.

**Comment by GutsySS13** [comment]
yeah i'm leaving that button as a normal button. as I said my button turned into something more like a volcano instead of a button and the other button didn't really look good either so i've given up. Maybe someone else has a good button or just leave it.

**Comment by Kwask** [comment]
no outspoken critics, gonna go ahead and merge dis one

**Comment by Rusty-Gravy** [comment]
Yeah I'll say it's a good move.
Any problems with the size and the icons can easily be updated.

**Pull request merged**
