### PR TITLE
The Rex-Written Legal Code

### PR DESCRIPTION
**Pull request by NovusLuna**
## New Pull Request

**Please follow this template to allow for better code management. PRs not following this template might be closed without notice.**

### Status (Ready for Merge, Do Not Merge, In Development)
Ready for Merge

### Changes introduced to the code/map
This brings in the new law code.

### Comments
This law code follows the same format as the old one, merely having variables changed to match the one I wrote that was approved at a Community Meeting.

### PR Checklist (Organisation-sided, leave this alone)
- [x] Code takes game balance into account.
- [x] Code is clear and understandable.
- [x] Code is commented.

_Maintainers: Do not merge code before the above steps are crossed out_

---
This change is [Reviewable](https://reviewable.io/reviews/apollo-community/apollostation/1390)

### CODE REVIEW

**Comment by Haldreithen** [comment]
No comments in the code and no changelog in there.

**Comment by NovusLuna** [comment]
What do you mean comments in the code? The // things? If so, I am not sure how those would be needed here.

**Comment by Haldreithen** [comment]
Saying what var does what, for example in the top to make it clear for anyone editting those files, since no commends like that were there as far as I know and well, now you're editing it

**Comment by NovusLuna** [comment]
That brings the point that...I was just editing variables for pre-existing files. Wouldn't that have fallen upon the creator? That and...those variables are the most self-explanatory variables I have ever seen.

**Comment by Haldreithen** [comment]
Sure, but comments are needed, kind of a requirement in the way we're organising the code right now. It would've fallen to the creator, but it's needed and wel, conviniently, you're editing the file

**Comment by NovusLuna** [comment]
Can they be added ex post facto? This request has been waiting a bit over two weeks since the Community Meeting that confirmed its use, and _months_ since we confirmed the use in-character.

**Comment by Haldreithen** [comment]
Sure, but you still need to add the changelog

**Comment by NovusLuna** [comment]
Which is what?

**Comment by Haldreithen** [comment]
https://github.com/Apollo-Community/ApolloStation/tree/master/html/changelogs

**Comment by InvidiaSH** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/apollo-community/apollostation/1390)*

**Comment by InvidiaSH** [comment]
Needs latest changes merge. There's a checkbox on the bottom of the menu on the right that allows us to do it for you.

**Pull request merged**
