### PR TITLE
Valan shipto centcom

### PR DESCRIPTION
**Pull request by GutsySS13**
Moved Valan's ship to centcom map, over under the merc ship's forward operating base as it's a fairly similar ship in size and destinations at least (internal access is centcom access). I've set the older standalone map to be removed.

Minor changes to internals, and enlarged prep room a little and added some clothes for admin dress up (got to love the Chicken and cardboard suit).

It seems that the arrivals destination area has been removed, I was going to add it back to make it easier to make a gantry should either shuttle need to fly there but I guess that's a project for another day.

### CODE REVIEW

**Comment by lmas** [comment]
Ignore the Travis error for now, it just failed to download the byond compiler..

**Comment by GutsySS13** [comment]
I was wondering what that was....

Thought it may be because we were using the older map on saturday and it hadn't been rolled back or something.

**Comment by GutsySS13** [comment]
Don't forget to remove the old z-admin-shuttle.dmm from loading that was put in in 3249b505cf200cbb53dd5c8a65e94808d1b7fab6 before this is merged, as obviously this will replace that and will probably clash.

PS, Stop flying my ship without meh :/ hope you're making lots of cash with cargo runs.

**Comment by GutsySS13** [comment]
I guess this is out of date now the map files have moved. i'll look at updating it

**Pull request closed without merging**
