### PR TITLE
Bar Upgrade!

### PR DESCRIPTION
**Pull request by Andrew-Fall**
## New Pull Request

**Please follow this template to allow for better code management. PRs not following this template might be closed without notice.**

### Status (Ready for Merge, Do Not Merge, In Development)
Ready for Merge

### Changes introduced to the code/map
Upgrades Bar and modifies some code so light tiles with the name "Disco floor" are disco.

### PR Checklist (Organisation-sided, leave this alone)
- [x] Code takes game balance into account.
- [x] Code is clear and understandable.
- [x] Code is commented.

_Maintainers: Do not merge code before the above steps are crossed out_

---
This change is [Reviewable](https://reviewable.io/reviews/apollo-community/apollostation/1382)

### CODE REVIEW

**Comment by Haldreithen** [comment]
Gonna need to fix that conflict before anything can be merged

**Comment by Andrew-Fall** [comment]
It isn't exactly giving me any details, just says the map file conflicts and that is it.
-edit 1-
I was thinking the new system was being silly, but idk.
-edit 2-
Ah, my branch is 14 commits behind, I will see if updating it will help.

**Comment by Andrew-Fall** [comment]
I was thinking the new system was being silly, but idk.

**Comment by Andrew-Fall** [comment]
Going to close and remake.

**Pull request closed without merging**
