### PR TITLE
Paint

### PR DESCRIPTION
**Pull request by Kwask**
Makes paint not crappy. Also phoron paint which blocks vorbis waves.

Examples:
[HOS office painted red](http://i.imgur.com/gHZZiNQ.png)
[Engine room painted with phoron paint](http://i.imgur.com/wP5TyE0.png)
[Different shades of paint](http://i.imgur.com/vSqcNPw.png)

### CODE REVIEW

**Comment by GutsySS13** [comment]
+1 for the paint. those walls looks really good

**Comment by Kwask** [comment]
I want to add paperdolling so you can add things like painted stripes and trim as well. Am also going to test paperdolling doors, because thats something that needs to happen sooner rather than later.

**Comment by nullbear** [comment]
Doors, Lockers, Canisters and Crates :D

**Comment by lmas** [comment]
:+1: Looks very nice. Will you update the map too and have each departments' walls painted? :D

**Comment by nullbear** [comment]
but can you mix them?

**Comment by Kwask** [comment]
@lmas, Absolutely. Need to figure out what style each department will get, though.
@nullbear Depends. I'll need to see how well initial results are, because I can imagine them coming out really badly.

**Comment by stuicey** [comment]
Would be nice for white walls in med/science with blue/purple stripe or pattern in my opinion

**Comment by Kwask** [comment]
I was thinking white with green stripe for medical, but purple for science sounds good. 
Not sure what engineering should have though

**Comment by lmas** [comment]
Orange obviously?

**Comment by nullbear** [comment]
Kwask, what about a 16 hue pallet, and white/gray/black?

**Comment by Kwask** [comment]
Engineer: http://i.imgur.com/vmicL76.png
Medical: http://i.imgur.com/DZFqYzA.png
Science: http://i.imgur.com/qDyuqGG.png

These aren't final colors, so it's still open for adjustment.

**Comment by GutsySS13** [comment]
if it's a vote I kinda like the single strip color for department. Maybe have the heads double or secure areas etc, I think this really adds to the game as it would happen in real life (just look at hospitals colour coding their department areas a bit, although it may get out of hand if each sub dept had their own colours.)

**Comment by Kwask** [comment]
I think each department will have its own style for sure, but I was to work with walls a bit before putting it as a default thing in-game.

**Pull request merged**
