### PR TITLE
Skrell hair

### PR DESCRIPTION
**Pull request by Fleegle2000**
This is my first attempt at merging a change with the repo, so I apologize if it doesn't work.

### CODE REVIEW

**Comment by Fleegle2000** [comment]
This should really be called Skrell eyes, but I named it before I realized it wasn't the hair.

**Comment by lmas** [comment]
```
Dear diary, today I was wrong.
```

Nice catch with their eyes! I kept thinking it was the tentacles.

But I think you misinterpreted what I wrote with moving the sprites and stuff. No need to be messing around in update_icons.dm and changing the eye icons, that will just add unnecessary apollo bloat for no good reason.

What I ment was, Stu added some antennae for the wryn to human_face.dmi (and there's some nucleation stuff too). It's a binary file and can't be merged with changes from bay12, alright.

So, we have to copy our human_face.dmi to the apollo dir, which you did. Sweet.
And then we replace the original human_face.dmi with one from bay12, so we get the skrell eyes back in.

Now we have one file with the regular bay12 sprites (and the eyes) in the original file and our custom sprites (such as the antennae) in the apollo dir. That fixed the skrell issue :D

Next we have to update [this code](https://github.com/stuicey/ApolloStation/blob/master/code/modules/mob/new_player/sprite_accessories.dm#L677), so it uses our custom human_face.dmi:

```
wry_antennae_default
name = "Antennae"
icon = 'icons/mob/apollo/Human_face.dmi'
icon_state = "wryn_antennae"
species_allowed = list("Wryn")
```

Ditto for the nucleations, just down below the wryn code block. This keeps the custom apollo stuff nice and tidy, in just one place. It's also easy to merge in changes from bay12 now.
And so we have working eyes for the skrell and still have the antennae for the wryn!

My apologies for this long post, but I wanted to help you understand how to write good code in an already messy codebase :D
I'm also going to be a bastard and deny you this PR and do the changes myself D: So you can see how I really ment.

**Comment by lmas** [comment]
See https://github.com/stuicey/ApolloStation/commit/9addcc6e1352efce6acf62f47791d8e89e89eb70, nice and easy eh? :D

**Comment by Fleegle2000** [comment]
Great - as long as the issue is fixed that's what's important. I now understand how the apollo sprites folder is meant to work.

**Pull request closed without merging**
