### PR TITLE
Add door jacks

### PR DESCRIPTION
**Pull request by halworsen**
Door jacks can force non-bolted airlocks open in 25 seconds but are noisy. You can instantly place door jacks in open airlocks. While there is a door jack on an airlock, it cannot be closed.

### CODE REVIEW

**Comment by halworsen** [comment]
Could use some new sprites, by the way.

**Comment by GutsySS13** [comment]
I'm not sure why something like this would be needed. We already have a number of ways doors can be opened (PAI's already have a door jack, and antags can use their encryptor). What makes this any different?

**Comment by halworsen** [comment]
This is intended for security (and atmos), which has to get someone else to open doors for them when they're running around doing their job. It's neither time-efficient nor safe (for the one opening up the doors).

Door jacks lets them get around if they really need to, and is a fair, but risky option for the poor antag. I see pAIs once in a blue moon, and antags will usually have better, more attractive options.

**Comment by lmas** [comment]
So this thing doesn't fit in [welded airlocks](https://github.com/Apollo-Community/ApolloStation/pull/464/files#diff-02c854f2288d252afedeb71454470b6aR984), right? What is that `operating` status for?

I would like it to have a big and bulky sprite in some shade of orange/red, kinda like the door jacks in the latest alien game. Tools like this is usually big, bulky and red IRL too.

**Comment by halworsen** [comment]
`operating` has to do with the door opening/closing or being emagged. So it won't won't work if the door is welded shut or already opening or closing.

**Pull request merged**
